### PR TITLE
feat: landing page added

### PR DESCRIPTION
**Pull request by ParthParolekar**
Landing page completed.
live: https://deploy-preview-12--electtron.netlify.app

### CODE REVIEW

**Review by nayyyhaa — APPROVED** [review]
Love the home screen animation + whole site responsiveness. Nice work!

**Review by VLeads — APPROVED** [review]
Landing page is awesome. Everything looks fine. Keep up doing the good work !!

**Review by anik31 — APPROVED** [review]
UI is good

**Comment by ParthParolekar** [comment]
Thank you @nayyyhaa @anik31  and @VLeads  for reviewing this PR
Merging now.

**Pull request merged**
