### PR TITLE
add: card component

### PR DESCRIPTION
**Pull request by ParthParolekar**
Added card component.

### CODE REVIEW

**Review by ApurvaSawant11 — APPROVED** [review]
Everything looks good to me :) nice work

**Comment by ParthParolekar** [comment]
> Everything looks good to me :) nice work

Thank you! :)

**Comment by yash9263** [comment]
looks good to me can remove comments in between styles

**Review by b0llu — APPROVED** [review]
Great work 👍

**Comment by ParthParolekar** [comment]
> looks good to me can remove comments in between styles

Thank you! I will remove the comments.

**Comment by ParthParolekar** [comment]
> Great work +1

Thank you! :)

**Pull request merged**
