### PR TITLE
feat: rating and toast component added

### PR DESCRIPTION
**Pull request by ParthParolekar**
Added rating and toast component.

### CODE REVIEW

**Review by vishal804 — APPROVED** [review]

**Comment by vishal804** [comment]
Everything looks Good

**Review by jalajcodes — APPROVED** [review]
Code looks good! Nice to see a different take on the rating component.

**Review by foolhardy21 — APPROVED** [review]
looks good. a prefix like color or c or clr can be added in colr variables for easier understanding.

**Comment by ParthParolekar** [comment]
> looks good. a prefix like color or c or clr can be added in colr variables for easier understanding.

I have already used these colors in a lot of places so It will be hard to change it now but I will make sure to name them with a prefix from now on. Thank you for the suggestion!

**Comment by ParthParolekar** [comment]
Thank you @vishal804 @foolhardy21  and @jalajcodes for the PR reviews. Merging now

**Pull request merged**
